### ISSUE TITLE
Need to add google lib in graddle 

### ISSUE THREAD

**Issue by johnjake** [softwarejoint/AndroidVideoEffects#1]
It will not run without the following: 

   MainApp.java

    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.android.support:exifinterface:28.0.0'
    implementation 'io.github.ypdieguez:cursor-recycler-adapter:1.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'

Is it possible to add emoji ? 

Thanks for the assume library. 

Best Regards 

John

**Comment by johnjake** [comment]
also layout should not contain activity_main.xml conflict with the library i guess.

**Comment by pankajsoni19** [comment]
Updated the library to use androidx.  for emoji's, please share a pull request
